parameters:
    zero_user.user.entity.class: Zero\Bundle\UserBundle\Entity\User
    zero_user.user.form.class: Zero\Bundle\UserBundle\Form\Type\UserType
    zero_user.user.manager.class: Zero\Bundle\UserBundle\Service\UserManager

    zero_user.user.group.entity.class: Zero\Bundle\UserBundle\Entity\User\Group
    zero_user.user.group.form.class: Zero\Bundle\UserBundle\Form\Type\User\GroupType
    zero_user.user.group.manager.class: Zero\Bundle\UserBundle\Service\User\GroupManager

services:
    zero_user.user.manager:
        class: %zero_user.user.manager.class%
        parent: zero_api.manager.abstract
        arguments: [%zero_user.user.entity.class%, %zero_user.user.form.class%]

    zero_user.user.group.manager:
        class: %zero_user.user.group.manager.class%
        parent: zero_api.manager.abstract
        arguments: [%zero_user.user.group.entity.class%, %zero_user.user.group.form.class%]