parameters:
    zero_user.user.entity.class: Zero\UserBundle\Entity\User
    zero_user.user.form.class: Zero\UserBundle\Form\UserType
    zero_user.user.manager.class: Zero\UserBundle\Service\UserManager

services:
    zero_user.user.manager:
        class: %zero_user.user.manager.class%
        parent: zero_api_base.manager.abstract
        arguments: [%zero_user.user.entity.class%, %zero_user.user.form.class%]