fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

zero_api_security_login:
    path:     /oauth/v2/auth_login
    defaults: { _controller: ZeroApiSecurityBundle:Security:login }

zero_api_security_login_check:
    path:     /oauth/v2/auth_login_check
    defaults: { _controller: ZeroApiSecurityBundle:Security:loginCheck }
