parameters:
    zero_api_base.manager.abstract.class: Zero\ApiBaseBundle\Manager\AbstractManager
    zero_api_base.listener.invalid_form_exception.class: Zero\ApiBaseBundle\Listener\InvalidFormExceptionListener

services:

    jms_serializer.identical_property_naming_strategy:
        class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

    jms_serializer.serialized_name_annotation_strategy:
        class: JMS\Serializer\Naming\SerializedNameAnnotationStrategy
        arguments: [@jms_serializer.identical_property_naming_strategy]

    jms_serializer.cache_naming_strategy:
        class: JMS\Serializer\Naming\CacheNamingStrategy
        arguments: [@jms_serializer.serialized_name_annotation_strategy]

    jms_serializer.naming_strategy:
        alias: jms_serializer.cache_naming_strategy

    zero_api_base.manager.abstract:
        class: %zero_api_base.manager.abstract.class%
        abstract: true
        calls:
            - [setObjectManager, [@doctrine.orm.default_entity_manager]]
            - [setFormFactory, [@form.factory]]

    zero_api_base.listener.invalid_form_exception:
        class: %zero_api_base.listener.invalid_form_exception.class%
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }