parameters:
    zero_api_base.manager.abstract.class: Zero\ApiBaseBundle\Manager\AbstractManager
    zero_api_base.listener.invalid_form_exception.class: Zero\ApiBaseBundle\Listener\InvalidFormExceptionListener

services:

    zero_api_base.manager.abstract:
        class: %zero_api_base.manager.abstract.class%
        abstract: true
        calls:
            - [setObjectManager, [@doctrine.orm.default_entity_manager]]
            - [setFormFactory, [@form.factory]]

    zero_api_base.listener.invalid_form_exception:
        class: %zero_api_base.listener.invalid_form_exception.class%
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }