zero_api_security:
    resource: "@ZeroApiSecurityBundle/Resources/config/routing.yml"
    prefix:   /

zero_user:
    resource: "@ZeroUserBundle/Resources/config/routing.yml"
    prefix:   /

#### API DOCS ####

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /docs/api

#### API ####
