zero_api_doc:
    resource: "@ZeroApiDocBundle/Resources/config/routing.yml"
    prefix:   /

#### API ####

api_zero_user:
    type: rest
    resource: "@ZeroUserBundle/Resources/config/routing-api.yml"
    prefix:   /api/