zero_o_auth:
    resource: "@ZeroOAuthBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /docs/api

zero_user:
    resource: "@ZeroUserBundle/Resources/config/routing.yml"
    prefix:   /

#### API ####

api_zero_user:
    type: rest
    resource: "@ZeroUserBundle/Resources/config/routing-api.yml"
    prefix:   /api/