<?php

namespace Zero\Bundle\UserBundle\Entity\User;

use Doctrine\ORM\EntityRepository;

/**
 * User:GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
}
